In [2]:
import pandas as pd
from gurobipy import *

In [5]:
data = pd.read_excel('박스규격_최적화_data.xlsx')
data

    주문번호  아이템코드     장     폭     고
0      1      1  29.2   9.1   8.0
1      2      2  21.2  12.0   9.2
2      2      3  28.5  12.3   7.0
3      2      4  28.3  19.1  12.0
4      3      5  26.8  18.0   1.9
..   ...    ...   ...   ...   ...
72    48     73  12.0   8.4   0.9
73    49     74  28.2   4.0   3.9
74    49     75  28.3   4.0   3.9
75    50     76  22.0  12.0   1.6
76    50     77   7.0   6.6   3.5

[77 rows x 5 columns]